//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnCodeUsWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        public int CalendarID { get; set; }
        public string CalendarTitle { get; set; }
        public string CalendarDesc { get; set; }
        public System.DateTime StartDay { get; set; }
        public System.DateTime EndDay { get; set; }
        public bool isFullDay { get; set; }
    }
}
